import type {
  PersistenceExemption,
  PersistenceFormat,
  PersistenceSchemaContract,
  PersistenceSchemaSource,
  PersistenceSiteKind,
  PersistenceSiteRule,
  StartupPhase,
  StoreDescriptor,
} from "./store-registry-types.ts";

const ALL_SITE_KINDS: readonly PersistenceSiteKind[] = [
  "database-open",
  "write-file",
  "append-file",
  "rename",
  "copy-file",
  "mkdir",
  "atomic-write",
  "persistent-store-constructor",
];

type StoreInput = {
  id: string;
  ownerModule: string;
  pathPatterns: string[];
  pathExclusions?: string[];
  pathKind?: "file" | "tree";
  format: PersistenceFormat;
  schemaSource: PersistenceSchemaSource;
  openEntry: string[];
  migrationEntry?: string[];
  firstPossibleOpenPhase?: StartupPhase;
  firstPossibleWritePhase?: StartupPhase;
  epochPolicy?: StoreDescriptor["epochPolicy"];
  checkpointPolicy?: string;
  restorePolicy?: string;
  affectedByEpochMigration?: boolean;
  identityContract: string;
  exemption?: StoreDescriptor["exemption"];
  compatibility?: string;
  siteRules?: PersistenceSiteRule[];
};

function runtimeSource(module: string, contract: string): PersistenceSchemaSource {
  return { kind: "runtime-contract", module, contract };
}

function directorySource(module: string, contract: string): PersistenceSchemaSource {
  return { kind: "directory-contract", module, contract };
}

function rules(
  sourceFiles: string[],
  reason: string,
  kinds: readonly PersistenceSiteKind[] = ALL_SITE_KINDS,
  linePattern?: string,
): PersistenceSiteRule[] {
  return sourceFiles.map((sourceFile) => ({
    sourceFile,
    kinds: [...kinds],
    ...(linePattern ? { linePattern } : {}),
    reason,
  }));
}

function defineStore(input: StoreInput): StoreDescriptor {
  let schemaContract: PersistenceSchemaContract;
  if (input.schemaSource.kind === "narrow-exemption") {
    schemaContract = {
      kind: "exempt",
      source: input.ownerModule,
      compatibility: input.compatibility ?? "No strict reader contract is claimed by this inventory.",
      reason: input.schemaSource.reason,
      expiresOn: input.schemaSource.expiresOn,
    };
  } else {
    schemaContract = {
      kind: input.schemaSource.kind === "directory-contract" ? "protocol" : "runtime-source",
      source: input.schemaSource.kind === "external-versioned"
        ? `${input.schemaSource.packageName} via ${input.schemaSource.lockfile}`
        : input.schemaSource.module,
      compatibility: input.compatibility
        ?? "The named runtime reader is canonical; this inventory does not imply stricter validation than runtime currently performs.",
    };
  }
  return Object.freeze({
    id: input.id,
    ownerModule: input.ownerModule,
    pathPattern: input.pathPatterns[0],
    pathPatterns: [...input.pathPatterns],
    pathExclusions: [...(input.pathExclusions ?? [])],
    pathKind: input.pathKind ?? "file",
    format: input.format,
    schemaSource: input.schemaSource,
    schemaContract,
    openEntry: [...input.openEntry],
    migrationEntry: [...(input.migrationEntry ?? [])],
    firstPossibleOpenPhase: input.firstPossibleOpenPhase ?? "engine_construct",
    firstPossibleWritePhase: input.firstPossibleWritePhase ?? "runtime_ready",
    epochPolicy: input.epochPolicy ?? "epoch-managed",
    checkpointPolicy: input.checkpointPolicy ?? "Included in a future epoch checkpoint unless the coordinator explicitly classifies it otherwise.",
    restorePolicy: input.restorePolicy ?? "Restore only through the owning module after reader compatibility is established.",
    affectedByEpochMigration: input.affectedByEpochMigration ?? true,
    identityContract: input.identityContract,
    exemption: input.exemption ?? null,
    siteRules: [...(input.siteRules ?? [])],
  });
}

export const PERSISTENT_STORES: readonly StoreDescriptor[] = Object.freeze([
  defineStore({
    id: "data-epoch-stamp",
    ownerModule: "shared/data-epoch.cjs",
    pathPatterns: ["data-epoch.json"],
    format: "json",
    schemaSource: runtimeSource("shared/data-epoch.cjs", "DATA_EPOCH stamp parser and atomic writer"),
    openEntry: ["assertAndStampDataEpoch"],
    firstPossibleOpenPhase: "epoch_preflight",
    firstPossibleWritePhase: "epoch_preflight",
    epochPolicy: "compatible",
    checkpointPolicy: "Never restore this stamp independently of the data tree it describes.",
    restorePolicy: "Recreate only as the final commit record of a coordinated epoch transition.",
    affectedByEpochMigration: false,
    identityContract: "One high-water stamp belongs to one canonical HANA_HOME.",
  }),
  defineStore({
    id: "server-runtime-info",
    ownerModule: "server/index.ts",
    pathPatterns: ["server-info.json"],
    format: "json",
    schemaSource: runtimeSource("server/index.ts", "server-info writer and desktop bootstrap reader"),
    openEntry: ["server/index.ts bootstrap"],
    firstPossibleOpenPhase: "transport_bind",
    firstPossibleWritePhase: "transport_bind",
    epochPolicy: "regenerable",
    checkpointPolicy: "Excluded; it is live process discovery state.",
    restorePolicy: "Regenerate after transport binding.",
    affectedByEpochMigration: false,
    identityContract: "At most one current server discovery record per HANA_HOME.",
    siteRules: rules(["server/index.ts"], "Writes live server discovery state.", ["write-file"], "serverInfoPath"),
  }),
  defineStore({
    id: "server-node-identity",
    ownerModule: "core/server-identity.ts",
    pathPatterns: ["server-node.json"],
    format: "json",
    schemaSource: runtimeSource("core/server-identity.ts", "server-node identity parser and ensureLocalIdentityRegistries seed"),
    openEntry: ["loadServerIdentity", "ensureLocalIdentityRegistries"],
    firstPossibleOpenPhase: "identity_seed",
    firstPossibleWritePhase: "identity_seed",
    checkpointPolicy: "Include with the identity registries for the same HANA_HOME.",
    restorePolicy: "Restore before remote transport accepts identity-bound requests.",
    identityContract: "serverNodeId is the stable identity of one HANA_HOME server node.",
    siteRules: rules(["core/server-identity.ts"], "Seeds the server-node identity registry.", ["atomic-write"], "serverNodePath"),
  }),
  defineStore({
    id: "user-studio-registries",
    ownerModule: "core/server-identity.ts",
    pathPatterns: ["users.json", "studios.json", "spaces.json"],
    format: "json",
    schemaSource: runtimeSource("core/server-identity.ts", "user/studio registry readers plus legacy spaces.json compatibility projection"),
    openEntry: ["loadServerIdentity", "ensureLocalIdentityRegistries"],
    migrationEntry: ["legacy spaces.json compatibility reader"],
    firstPossibleOpenPhase: "identity_seed",
    firstPossibleWritePhase: "identity_seed",
    checkpointPolicy: "Checkpoint users and studios together; retain spaces.json only as a legacy migration source.",
    restorePolicy: "Restore users/studios before dependent grants or mounts; never project newer studio state back into spaces.json.",
    identityContract: "userId and studioId are durable identities; spaces.json is a legacy locator/source only.",
    siteRules: [
      ...rules(["core/server-identity.ts"], "Seeds user or studio identity registries.", ["atomic-write"], "(?:usersPath|studiosPath)"),
      ...rules(["core/local-user-account.ts"], "Updates the local user record in users.json.", ["atomic-write"], "USERS_FILE"),
    ],
  }),
  defineStore({
    id: "local-user-auth",
    ownerModule: "core/local-user-account.ts",
    pathPatterns: ["local-user-auth.json"],
    format: "json",
    schemaSource: runtimeSource("core/local-user-account.ts", "local authentication secret reader and atomic serializer"),
    openEntry: ["ensureLocalUserAccount", "authenticateLocalUser"],
    firstPossibleOpenPhase: "identity_seed",
    firstPossibleWritePhase: "identity_seed",
    checkpointPolicy: "Checkpoint as permission-preserving secret material with its matching users.json identity.",
    restorePolicy: "Restore atomically before local authentication is enabled.",
    identityContract: "The credential belongs to the local userId in the same HANA_HOME.",
    siteRules: rules(["core/local-user-account.ts"], "Writes the local user authentication record.", ["atomic-write"], "LOCAL_USER_AUTH_FILE"),
  }),
  defineStore({
    id: "device-access-registries",
    ownerModule: "core/device-registry.ts",
    pathPatterns: ["devices.json", "device-credentials.json", "pairing-sessions.json"],
    format: "json",
    schemaSource: runtimeSource("core/device-registry.ts", "device, credential, and pairing-session validators/serializers"),
    openEntry: ["ensureDeviceAccessRegistries", "loadDeviceAccessRegistries"],
    firstPossibleOpenPhase: "identity_seed",
    firstPossibleWritePhase: "identity_seed",
    checkpointPolicy: "Checkpoint all three registries as one referential set.",
    restorePolicy: "Restore atomically before paired-device authentication is enabled.",
    identityContract: "deviceId, credentialId, and pairingSessionId are durable cross-registry keys.",
    siteRules: rules(["core/device-registry.ts"], "Writes one member of the device-access registry set."),
  }),
  defineStore({
    id: "server-network-config",
    ownerModule: "core/server-network-config.ts",
    pathPatterns: ["server-network.json"],
    format: "json",
    schemaSource: runtimeSource("core/server-network-config.ts", "server network mode/listen configuration validator"),
    openEntry: ["ensureServerNetworkConfig", "loadServerNetworkConfig"],
    firstPossibleOpenPhase: "identity_seed",
    firstPossibleWritePhase: "identity_seed",
    checkpointPolicy: "Include as operator configuration.",
    restorePolicy: "Validate before binding; invalid restored values fail explicitly.",
    identityContract: "One network configuration belongs to one HANA_HOME server.",
    siteRules: rules(["core/server-network-config.ts"], "Writes validated server network configuration."),
  }),
  defineStore({
    id: "studio-mount-registry",
    ownerModule: "core/studio-mounts.ts",
    pathPatterns: ["studio-mounts.json"],
    format: "json",
    schemaSource: runtimeSource("core/studio-mounts.ts", "schemaVersion 1 studio mount registry validator"),
    openEntry: ["ensureStudioMountRegistry", "loadStudioMountRegistry"],
    firstPossibleOpenPhase: "identity_seed",
    firstPossibleWritePhase: "identity_seed",
    checkpointPolicy: "Include mount declarations but never copy external mounted content implicitly.",
    restorePolicy: "Restore declarations, then revalidate each external root before granting access.",
    identityContract: "mountId is durable; external paths are locators that require revalidation.",
    siteRules: rules(["core/studio-mounts.ts"], "Writes the studio mount registry."),
  }),
  defineStore({
    id: "web-session-registry",
    ownerModule: "core/web-session-store.ts",
    pathPatterns: ["web-sessions.json"],
    format: "json",
    schemaSource: runtimeSource("core/web-session-store.ts", "web session registry validator, expiry, and serializer"),
    openEntry: ["ensureWebSessionRegistry", "WebSessionStore"],
    firstPossibleOpenPhase: "identity_seed",
    firstPossibleWritePhase: "identity_seed",
    checkpointPolicy: "Exclude expired sessions; preserve only live sessions when auth continuity is required.",
    restorePolicy: "Load through WebSessionStore so expiry and validation run before use.",
    identityContract: "webSessionId is durable only for the validated lifetime of its user-bound session.",
    siteRules: rules(["core/web-session-store.ts"], "Writes the web session registry."),
  }),
  defineStore({
    id: "security-grants",
    ownerModule: "core/grant-registry.ts",
    pathPatterns: ["security/grants.json", "security/grants.json.corrupt-{timestamp}", "security/grants.json.corrupt-{timestamp}.reason.txt"],
    format: "json",
    schemaSource: runtimeSource("core/grant-registry.ts", "grant registry validator, quarantine, and atomic serializer"),
    openEntry: ["ensureGrantRegistry", "loadGrantRegistry"],
    firstPossibleOpenPhase: "identity_seed",
    firstPossibleWritePhase: "identity_seed",
    checkpointPolicy: "Checkpoint the validated registry; quarantine evidence is diagnostic and optional.",
    restorePolicy: "Validate before enabling grants; corrupt input is quarantined and fails visibly.",
    identityContract: "grantId and its principal/resource scope are the durable authorization identity.",
    siteRules: rules(["core/grant-registry.ts"], "Writes, repairs, or quarantines the grant registry."),
  }),
  defineStore({
    id: "execution-leases",
    ownerModule: "core/execution-lease-registry.ts",
    pathPatterns: ["security/execution-leases.json"],
    format: "json",
    schemaSource: runtimeSource("core/execution-lease-registry.ts", "execution lease registry validator and atomic serializer"),
    openEntry: ["ensureExecutionLeaseRegistry", "loadExecutionLeaseRegistry"],
    firstPossibleOpenPhase: "identity_seed",
    firstPossibleWritePhase: "identity_seed",
    checkpointPolicy: "Exclude expired leases and preserve live leases only with their grant principals.",
    restorePolicy: "Reload through the lease validator and re-evaluate expiry before execution resumes.",
    identityContract: "leaseId is durable only within its principal, grant, and expiry scope.",
    siteRules: rules(["core/execution-lease-registry.ts"], "Writes the execution lease registry."),
  }),
  defineStore({
    id: "security-key-material",
    ownerModule: "core/resource-ticket-service.ts",
    pathPatterns: [
      "security/resource-ticket-key",
      "security/plugin-asset-session-key",
      "security/plugin-iframe-ticket-key",
      "security/plugin-surface-session-key",
    ],
    format: "mixed-directory",
    schemaSource: directorySource("core/resource-ticket-service.ts", "independent 0600 random key-file protocols for resource and plugin ticket services"),
    openEntry: ["security ticket service construction"],
    firstPossibleOpenPhase: "engine_construct",
    firstPossibleWritePhase: "engine_construct",
    checkpointPolicy: "Checkpoint exact bytes with restrictive permissions when continuity of issued tickets is required.",
    restorePolicy: "Restore before constructing the matching service; missing keys rotate and invalidate old tickets.",
    identityContract: "Each fixed filename is a distinct service signing boundary; key bytes must never be interchanged.",
    siteRules: rules([
      "core/resource-ticket-service.ts",
      "core/plugin-asset-session-service.ts",
      "core/plugin-iframe-ticket-service.ts",
      "core/plugin-surface-session-service.ts",
    ], "Creates one service-specific signing key with mode 0600."),
  }),
  defineStore({
    id: "security-audit-log",
    ownerModule: "core/security-audit-log.ts",
    pathPatterns: ["logs/security-audit.jsonl"],
    format: "append-only-log",
    schemaSource: runtimeSource("core/security-audit-log.ts", "one JSON object per append-only security audit line"),
    openEntry: ["appendSecurityAuditRecord"],
    firstPossibleOpenPhase: "runtime_ready",
    firstPossibleWritePhase: "runtime_ready",
    checkpointPolicy: "Preserve byte order and complete lines; never merge by object key.",
    restorePolicy: "Append only after the restored final newline; malformed tails require explicit repair.",
    identityContract: "Log sequence and record timestamps provide provenance; the path is a fixed locator.",
    siteRules: rules(["core/security-audit-log.ts"], "Appends a security audit record."),
  }),
  defineStore({
    id: "user-preferences",
    ownerModule: "core/preferences-manager.ts",
    pathPatterns: ["user/preferences.json"],
    format: "json",
    schemaSource: runtimeSource("core/preferences-manager.ts", "PreferencesManager defaults, coercion, and _dataVersion migration driver"),
    openEntry: ["new PreferencesManager"],
    migrationEntry: ["core/migrations.ts runMigrations"],
    firstPossibleOpenPhase: "first_run_seed",
    firstPossibleWritePhase: "first_run_seed",
    compatibility: "PreferencesManager is intentionally permissive; _dataVersion is the legacy migration cursor, not a strict schema validator.",
    identityContract: "One preferences document belongs to the local user in one HANA_HOME.",
    siteRules: [
      ...rules(["core/preferences-manager.ts"], "Reads and atomically writes user preferences."),
      ...rules(["core/engine.ts"], "Constructs the preferences owner.", ["persistent-store-constructor"], "PreferencesManager"),
    ],
  }),
  defineStore({
    id: "provider-state",
    ownerModule: "core/provider-catalog.ts",
    pathPatterns: [
      "provider-catalog.json",
      "added-models.yaml",
      "models.json",
      "auth.json",
      "providers/{providerId}/manifest.json",
      "providers/{providerId}/provider.json",
    ],
    format: "mixed-directory",
    schemaSource: directorySource("core/provider-catalog.ts", "ProviderCatalogStore plus provider plugin/config runtime readers"),
    openEntry: ["new ProviderRegistry", "new ProviderCatalogStore"],
    migrationEntry: ["core/migrate-providers.ts", "core/provider-auth-migration.ts", "core/provider-media-config.ts"],
    firstPossibleOpenPhase: "engine_construct",
    firstPossibleWritePhase: "engine_construct",
    identityContract: "providerId is the durable key; YAML/JSON paths are storage locators.",
    siteRules: rules([
      "core/local-provider-plugin-store.ts",
      "core/migrate-providers.ts",
      "core/model-sync.ts",
      "core/provider-auth-migration.ts",
      "core/provider-catalog.ts",
      "core/provider-media-config.ts",
      "core/provider-registry.ts",
      "server/routes/providers.ts",
    ], "Owns provider catalog, authentication, model compatibility, or local provider plugin state."),
  }),
  defineStore({
    id: "agent-profile",
    ownerModule: "core/agent-manager.ts",
    pathPatterns: [
      "agents/{agentId}/config.yaml",
      "agents/{agentId}/identity.md",
      "agents/{agentId}/ishiki.md",
      "agents/{agentId}/public-ishiki.md",
      "agents/{agentId}/appearance-summary.json",
      "agents/{agentId}/avatars/{fileName}",
      "agents/{agentId}/pinned.md",
      "agents/{agentId}/channels.md",
      "user/avatars/{fileName}",
    ],
    pathKind: "file",
    format: "mixed-directory",
    schemaSource: directorySource("core/agent-manager.ts", "agent config and authored Markdown/image profile protocol"),
    openEntry: ["AgentManager.loadAgents", "new HanaAgent"],
    migrationEntry: ["lib/compat/checks/config-yaml.ts"],
    firstPossibleOpenPhase: "first_run_seed",
    firstPossibleWritePhase: "first_run_seed",
    identityContract: "agentId owns the profile; each filename has a fixed semantic role.",
    siteRules: [
      ...rules(["core/agent-manager.ts"], "Creates or edits agent profile material.", ["write-file", "copy-file", "mkdir"]),
      ...rules(["lib/agent-appearance-summary.ts", "lib/compat/checks/config-yaml.ts", "server/routes/agents.ts", "server/routes/avatar.ts", "server/routes/config.ts"], "Reads, repairs, or edits agent/user profile material.", ["write-file", "copy-file", "rename", "mkdir", "atomic-write"]),
    ],
  }),
  defineStore({
    id: "agent-facts-sqlite",
    ownerModule: "lib/memory/fact-store.ts",
    pathPatterns: ["agents/{agentId}/memory/facts.db"],
    format: "sqlite",
    schemaSource: { kind: "sqlite-runtime", module: "lib/memory/fact-store.ts", contract: "FactStore runtime DDL, PRAGMA user_version, and introspection" },
    openEntry: ["new FactStore"],
    migrationEntry: ["FactStore store-local migrations", "lib/compat/checks/facts-db.ts"],
    compatibility: "The FactStore runtime and its introspection are canonical; test-only v1 DDL is migration fixture data, never the schema source.",
    identityContract: "One facts database belongs to one agentId; SQLite user_version is store-local and never DATA_EPOCH.",
    siteRules: [
      ...rules(["lib/memory/fact-store.ts", "lib/compat/checks/facts-db.ts", "hub/channel-router.ts"], "Opens or repairs the canonical per-agent facts database."),
      ...rules(["core/agent.ts", "lib/character-cards/service.ts", "server/routes/config.ts"], "Constructs or migrates a FactStore.", ["database-open", "persistent-store-constructor"], "(?:FactStore|better-sqlite3|new Database)"),
    ],
  }),
  defineStore({
    id: "agent-memory",
    ownerModule: "lib/memory/compile.ts",
    pathPatterns: [
      "agents/{agentId}/memory/memory.md",
      "agents/{agentId}/memory/facts.md",
      "agents/{agentId}/memory/today.md",
      "agents/{agentId}/memory/week.md",
      "agents/{agentId}/memory/longterm.md",
      "agents/{agentId}/memory/editable-facts-state.json",
      "agents/{agentId}/memory/today-state.json",
      "agents/{agentId}/memory/daily-state.json",
      "agents/{agentId}/memory/pinned-memory.json",
      "agents/{agentId}/memory/summaries/{sessionId}.json",
      "agents/{agentId}/memory/daily/{date}.md",
      "agents/{agentId}/memory/memories.db",
      "agents/{agentId}/memory/.v2-migrated",
    ],
    format: "mixed-directory",
    schemaSource: directorySource("lib/memory/compiled-memory-state.ts", "compiled memory, rolling-summary, pinned-memory, and daily-state runtime readers"),
    openEntry: ["HanaAgent.init", "memory ticker and summary stores"],
    migrationEntry: ["HanaAgent v1 memories.db import", "core/migrations.ts memory migrations"],
    identityContract: "agentId owns long-term memory; session summaries are keyed by sessionId, never by sessionPath.",
    siteRules: [
      ...rules(["core/agent.ts"], "Creates the memory directory and records legacy memories.db import state.", ["write-file", "mkdir"]),
      ...rules([
        "lib/memory/cache-snapshot-observation.ts",
        "lib/memory/compile.ts",
        "lib/memory/compiled-memory-snapshot.ts",
        "lib/memory/compiled-memory-state.ts",
        "lib/memory/config-loader.ts",
        "lib/memory/memory-ticker.ts",
        "lib/memory/pinned-memory-store.ts",
        "lib/memory/session-summary.ts",
      ], "Writes a named per-agent memory protocol file."),
    ],
  }),
  defineStore({
    id: "session-manifest-sqlite",
    ownerModule: "core/session-manifest/store.ts",
    pathPatterns: ["session-manifest.db", "session-manifest.db-wal", "session-manifest.db-shm"],
    format: "sqlite",
    schemaSource: { kind: "sqlite-runtime", module: "core/session-manifest/store.ts", contract: "SessionManifestStore runtime DDL and store-local PRAGMA user_version" },
    openEntry: ["new SessionManifestStore"],
    migrationEntry: ["core/session-manifest/legacy-migration.ts"],
    firstPossibleOpenPhase: "engine_construct",
    firstPossibleWritePhase: "engine_construct",
    identityContract: "sessionId is the durable identity; sessionPath is only the current JSONL locator.",
    siteRules: [
      ...rules(["core/session-manifest/store.ts", "core/session-manifest/db-files.ts", "core/session-manifest/legacy-migration.ts"], "Opens, migrates, or manages files for session-manifest.db."),
      ...rules(["core/engine.ts"], "Constructs the manifest store during engine construction.", ["persistent-store-constructor"], "SessionManifestStore"),
    ],
  }),
  defineStore({
    id: "session-jsonl",
    ownerModule: "core/session-coordinator.ts",
    pathPatterns: [
      "agents/{agentId}/sessions/{sessionId}.jsonl",
      "agents/{agentId}/sessions/archived/{sessionId}.jsonl",
      "agents/{agentId}/activity/{sessionId}.jsonl",
      "agents/{agentId}/subagent-sessions/{sessionId}.jsonl",
    ],
    format: "jsonl",
    schemaSource: {
      kind: "external-versioned",
      packageName: "@earendil-works/pi-coding-agent",
      lockfile: "package-lock.json integrity",
      versionSource: "Pi CURRENT_SESSION_VERSION",
      extensions: ["core/session-jsonl-file.ts repair contract", "core/session-coordinator.ts Hana metadata extensions"],
    },
    openEntry: ["SessionCoordinator create/restore", "Pi SessionManager"],
    migrationEntry: ["core/session-jsonl-file.ts", "core/migrations.ts session JSONL migrations"],
    compatibility: "The locked Pi package schema/version plus Hana repair and extension readers are canonical; Hana does not duplicate Pi's session schema.",
    identityContract: "sessionId is identity. sessionPath is a mutable locator and must be resolved at boundaries before keyed state access.",
    siteRules: [
      ...rules([
        "core/session-coordinator.ts",
        "core/session-jsonl-file.ts",
        "core/slash-commands/session-ops.ts",
        "hub/agent-executor.ts",
      ], "Creates, repairs, archives, restores, or appends session JSONL locators."),
      ...rules(["server/routes/sessions.ts"], "Archives or restores a session JSONL locator.", ["mkdir", "rename"]),
    ],
  }),
  defineStore({
    id: "session-sidecars",
    ownerModule: "core/bridge-session-manager.ts",
    pathPatterns: [
      "agents/{agentId}/sessions/session-meta.json",
      "agents/{agentId}/sessions/session-titles.json",
      "agents/{agentId}/sessions/bridge/bridge-sessions.json",
      "agents/{agentId}/sessions/session-vision-notes.json",
      "agents/{agentId}/subagent-sessions/session-meta.json",
    ],
    format: "json",
    schemaSource: runtimeSource("core/bridge-session-manager.ts", "bridge index, legacy session metadata, title, and vision sidecar readers"),
    openEntry: ["SessionCoordinator", "BridgeSessionManager", "VisionBridge"],
    migrationEntry: ["core/session-manifest/legacy-migration.ts", "core/migrations.ts"],
    identityContract: "Entries are keyed by sessionId where available; any sessionPath field is only a locator compatibility field.",
    siteRules: rules(["core/bridge-session-manager.ts", "core/vision-bridge.ts"], "Writes a session-owned sidecar or bridge index."),
  }),
  defineStore({
    id: "session-files",
    ownerModule: "lib/session-files/session-file-registry.ts",
    pathPatterns: ["session-files/{sessionHash}"],
    pathKind: "tree",
    format: "mixed-directory",
    schemaSource: directorySource("lib/session-files/session-file-registry.ts", "SessionFile payload naming, v1 sidecar, ownership, and 72-hour cold-session cleanup protocol"),
    openEntry: ["SessionFileRegistry"],
    migrationEntry: ["core/migrations.ts SessionFile migrations"],
    checkpointPolicy: "Checkpoint sidecar and payload bytes together; exclude expired cold-session cache entries.",
    restorePolicy: "Restore by sessionId ownership and rebuild locators through SessionFileRegistry.",
    identityContract: "SessionFile ID and owning sessionId are identities; the hash directory and payload paths are locators.",
    siteRules: rules([
      "lib/session-files/bridge-inbound-files.ts",
      "lib/session-files/browser-screenshot-file.ts",
      "lib/session-files/session-file-registry.ts",
      "hub/index.ts",
    ], "Stages payload bytes or updates SessionFile sidecars under the managed cache."),
  }),
  defineStore({
    id: "session-drafts-and-projects",
    ownerModule: "core/input-drafts-store.ts",
    pathPatterns: ["input-drafts.v1.json", "user/session-projects.json"],
    format: "json",
    schemaSource: runtimeSource("core/input-drafts-store.ts", "InputDraftsStore and SessionProjectCatalogStore normalizers"),
    openEntry: ["new InputDraftsStore", "new SessionProjectCatalogStore"],
    firstPossibleOpenPhase: "engine_construct",
    firstPossibleWritePhase: "engine_construct",
    identityContract: "Draft/project records are keyed by sessionId; any saved sessionPath is a locator only.",
    siteRules: [
      ...rules(["core/input-drafts-store.ts", "core/session-project-catalog-store.ts"], "Owns session drafts or project associations."),
      ...rules(["core/engine.ts"], "Constructs draft/project stores.", ["persistent-store-constructor"], "(?:InputDraftsStore|SessionProjectCatalogStore)"),
    ],
  }),
  defineStore({
    id: "channels",
    ownerModule: "lib/channels/channel-store.ts",
    pathPatterns: ["channels/{channelId}.yaml"],
    format: "yaml",
    schemaSource: runtimeSource("lib/channels/channel-store.ts", "channel YAML parser, serializer, and generation contract"),
    openEntry: ["ChannelManager", "ChannelStore"],
    migrationEntry: ["core/migrations.ts channel migrations"],
    identityContract: "channelId is durable; YAML filename is its canonical locator.",
    siteRules: [
      ...rules(["core/channel-manager.ts", "lib/channels/channel-store.ts"], "Creates the channel root or writes channel generations."),
      ...rules(["core/engine.ts"], "Creates the channel root.", ["mkdir"], "channelsDir"),
    ],
  }),
  defineStore({
    id: "desk-activity",
    ownerModule: "lib/desk/activity-store.ts",
    pathPatterns: ["agents/{agentId}/desk/activities.json"],
    format: "mixed-directory",
    schemaSource: directorySource("lib/desk/activity-store.ts", "activity index and activity-session JSONL lifecycle"),
    openEntry: ["new ActivityStore", "DeskManager"],
    identityContract: "activityId/sessionId identify records; session files remain agent-owned locators.",
    siteRules: [
      ...rules(["lib/desk/activity-store.ts", "lib/desk/desk-manager.ts"], "Writes the activity index or activity session lifecycle state."),
      ...rules(["core/agent-manager.ts"], "Constructs an ActivityStore for an agent.", ["persistent-store-constructor"], "ActivityStore"),
    ],
  }),
  defineStore({
    id: "cron-automation",
    ownerModule: "lib/desk/cron-store.ts",
    pathPatterns: [
      "agents/{agentId}/desk/cron-jobs.json",
      "agents/{agentId}/desk/cron-runs/{runId}.json",
      "studios/{studioId}/desk/cron-jobs.json",
      "studios/{studioId}/desk/cron-runs/{runId}.json",
    ],
    format: "mixed-directory",
    schemaSource: directorySource("lib/desk/cron-store.ts", "CronStore job registry and run receipt protocol"),
    openEntry: ["new CronStore", "StudioCronService"],
    migrationEntry: ["core/migrations.ts cron migrations"],
    identityContract: "jobId and runId are scoped to their agentId or studioId owner.",
    siteRules: [
      ...rules(["lib/desk/cron-store.ts", "core/studio-cron-service.ts"], "Writes cron jobs or execution receipts."),
      ...rules(["core/agent.ts"], "Constructs an agent or studio CronStore.", ["persistent-store-constructor"], "CronStore"),
    ],
  }),
  defineStore({
    id: "agent-authored-records",
    ownerModule: "lib/tools/experience.ts",
    pathPatterns: [
      "user/user.md",
      "agents/{agentId}/dm/{peerId}.md",
      "agents/{agentId}/experience.md",
      "agents/{agentId}/experience/{category}.md",
      "agents/{agentId}/diary/{date}.md",
    ],
    format: "markdown",
    schemaSource: directorySource("lib/tools/experience.ts", "user profile, DM, experience index, and diary Markdown conventions"),
    openEntry: ["user profile and agent tools"],
    identityContract: "Files are owned by userId or agentId; peer/category/date names define stable logical records.",
    siteRules: rules([
      "lib/tools/dm-tool.ts",
      "lib/tools/experience.ts",
      "lib/user-profile-store.ts",
      "lib/diary/diary-writer.ts",
    ], "Writes a user- or agent-authored Markdown record."),
  }),
  defineStore({
    id: "agent-phone",
    ownerModule: "lib/conversations/agent-phone-projection.ts",
    pathPatterns: [
      "agents/{agentId}/phone/conversations/{conversationId}.md",
      "agents/{agentId}/phone/session-runtime/{conversationId}.json",
    ],
    format: "mixed-directory",
    schemaSource: directorySource("lib/conversations/agent-phone-projection.ts", "phone projection Markdown and session-runtime JSON readers"),
    openEntry: ["Agent Phone conversation runtime"],
    migrationEntry: ["core/migrations.ts Agent Phone projection migration"],
    identityContract: "conversationId is identity within agentId; projection/runtime paths are locators.",
    siteRules: rules(["lib/conversations/agent-phone-projection.ts", "lib/conversations/agent-phone-runtime.ts"], "Writes Agent Phone projection or runtime state."),
  }),
  defineStore({
    id: "workflow-state",
    ownerModule: "lib/workflow/journal.ts",
    pathPatterns: [
      "agents/{agentId}/workflow-journals/{runId}.jsonl",
      "agents/{agentId}/workflow-sessions/{runId}",
      "workflow-activity.json",
    ],
    pathKind: "file",
    format: "mixed-directory",
    schemaSource: directorySource("lib/workflow/journal.ts", "WorkflowJournal append protocol and WorkflowActivityStore runtime reader"),
    openEntry: ["WorkflowJournal", "new WorkflowActivityStore"],
    identityContract: "runId is workflow identity; activity entries reference that ID, not the journal path.",
    siteRules: [
      ...rules(["lib/workflow/journal.ts", "lib/workflow-activity-store.ts", "lib/tools/workflow-tool.ts"], "Writes workflow journal, session, or activity state."),
      ...rules(["server/index.ts"], "Constructs the workflow activity store.", ["persistent-store-constructor"], "WorkflowActivityStore"),
    ],
  }),
  defineStore({
    id: "subagent-state",
    ownerModule: "lib/subagent-run-store.ts",
    pathPatterns: ["subagent-runs.json", "subagent-threads.json"],
    format: "json",
    schemaSource: runtimeSource("lib/subagent-run-store.ts", "SubagentRunStore and SubagentThreadStore permissive runtime readers"),
    openEntry: ["new SubagentRunStore", "new SubagentThreadStore"],
    migrationEntry: ["core/migrations.ts subagent identity migrations"],
    compatibility: "Current readers are permissive and repair legacy shapes; this inventory does not claim strict validation.",
    identityContract: "runId and threadId are durable; parent session references prefer sessionId and retain path only as a locator.",
    siteRules: [
      ...rules(["lib/subagent-run-store.ts", "lib/subagent-thread-store.ts", "lib/subagent-executor-metadata.ts"], "Writes subagent run, thread, or executor metadata."),
      ...rules(["server/index.ts"], "Constructs subagent stores.", ["persistent-store-constructor"], "Subagent(?:Run|Thread)Store"),
    ],
  }),
  defineStore({
    id: "plugin-task-registry",
    ownerModule: "lib/task-registry.ts",
    pathPatterns: [".ephemeral/plugin-tasks.json"],
    format: "json",
    schemaSource: runtimeSource("lib/task-registry.ts", "TaskRegistry task/schedule normalization and persistence serializer"),
    openEntry: ["new TaskRegistry"],
    firstPossibleOpenPhase: "engine_construct",
    firstPossibleWritePhase: "engine_construct",
    checkpointPolicy: "Include persisted task/schedule metadata when plugin recovery must survive the checkpoint; handlers remain runtime-only.",
    restorePolicy: "Load through TaskRegistry, then let each plugin register its handler before recovery is attempted.",
    identityContract: "taskId/scheduleId are durable registry keys; parent session ownership prefers sessionId.",
    siteRules: [
      ...rules(["lib/task-registry.ts"], "Persists plugin task and schedule metadata."),
      ...rules(["core/engine.ts"], "Constructs the plugin task registry.", ["persistent-store-constructor"], "TaskRegistry"),
    ],
  }),
  defineStore({
    id: "deferred-result-state",
    ownerModule: "lib/deferred-result-store.ts",
    pathPatterns: [".ephemeral/deferred-tasks.json"],
    format: "json",
    schemaSource: runtimeSource("lib/deferred-result-store.ts", "DeferredResultStore normalization, seven-day cleanup, and atomic serializer"),
    openEntry: ["new DeferredResultStore"],
    migrationEntry: ["core/migrations.ts deferred result migrations"],
    firstPossibleOpenPhase: "engine_construct",
    firstPossibleWritePhase: "engine_construct",
    checkpointPolicy: "Include undelivered deferred results needed for restart notification; expired/delivered entries may be pruned.",
    restorePolicy: "Load through DeferredResultStore so cleanup and delivery flags are applied before events resume.",
    identityContract: "taskId is durable; session ownership prefers sessionId and retains sessionPath only as a locator.",
    siteRules: [
      ...rules(["lib/deferred-result-store.ts"], "Persists deferred task/result delivery state."),
      ...rules(["server/index.ts"], "Constructs the deferred result store.", ["persistent-store-constructor"], "DeferredResultStore"),
    ],
  }),
  defineStore({
    id: "terminal-session-state",
    ownerModule: "lib/terminal/terminal-session-manager.ts",
    pathPatterns: [
      ".ephemeral/terminal-sessions/{terminalId}.json",
      ".ephemeral/terminal-sessions/{terminalId}.jsonl",
    ],
    format: "mixed-directory",
    schemaSource: directorySource("lib/terminal/terminal-session-manager.ts", "terminal metadata JSON plus ordered transcript JSONL protocol"),
    openEntry: ["new TerminalSessionManager"],
    firstPossibleOpenPhase: "runtime_ready",
    firstPossibleWritePhase: "runtime_ready",
    checkpointPolicy: "Preserve metadata and transcript together only for diagnostic continuity; a live PTY handle is never checkpointed.",
    restorePolicy: "Load through TerminalSessionManager; persisted running entries are historical metadata, not resumable processes.",
    identityContract: "terminalId identifies metadata/transcript; session ownership must resolve to sessionId before keyed access.",
    siteRules: rules(["lib/terminal/terminal-session-manager.ts"], "Writes terminal metadata or appends ordered transcript chunks."),
  }),
  defineStore({
    id: "skill-translation-cache",
    ownerModule: "lib/skills/skill-name-translation-cache.ts",
    pathPatterns: [".ephemeral/skill-name-translations.json"],
    format: "json",
    schemaSource: runtimeSource("lib/skills/skill-name-translation-cache.ts", "CACHE_VERSION and translation normalization"),
    openEntry: ["skill name translation lookup"],
    firstPossibleOpenPhase: "runtime_ready",
    firstPossibleWritePhase: "runtime_ready",
    epochPolicy: "regenerable",
    checkpointPolicy: "Excluded; translations are a versioned cache.",
    restorePolicy: "Delete and regenerate when CACHE_VERSION or normalization becomes incompatible.",
    affectedByEpochMigration: false,
    identityContract: "Cache keys derive from skill names/content; the file path is not a durable identity.",
    siteRules: rules(["lib/skills/skill-name-translation-cache.ts"], "Atomically updates the versioned skill translation cache."),
  }),
  defineStore({
    id: "usage-ledger",
    ownerModule: "lib/llm/usage-ledger.ts",
    pathPatterns: ["usage-ledger.json"],
    format: "json",
    schemaSource: runtimeSource("lib/llm/usage-ledger.ts", "UsageLedger reader and atomic serializer"),
    openEntry: ["new UsageLedger"],
    identityContract: "Usage buckets are keyed by their runtime dimensions inside one HANA_HOME ledger.",
    siteRules: rules(["lib/llm/usage-ledger.ts"], "Writes the usage ledger."),
  }),
  defineStore({
    id: "installed-plugins",
    ownerModule: "core/plugin-manager.ts",
    pathPatterns: [
      "plugins/{pluginId}",
      "plugin-installs.json",
      "plugin-backups/{pluginId}",
      "plugin-marketplace/marketplace.json",
    ],
    pathKind: "tree",
    format: "mixed-directory",
    schemaSource: directorySource("core/plugin-manager.ts", "installed manifest, install receipt, backup, and source-package directory protocols"),
    openEntry: ["PluginManager.loadPlugins"],
    migrationEntry: ["plugin installation compatibility checks"],
    identityContract: "pluginId from manifest is identity; versions and directories are locators/generations.",
    siteRules: [
      ...rules(["lib/plugin-install-backups.ts", "lib/plugin-install-records.ts"], "Backs up or records an installed plugin package."),
      ...rules(["server/routes/plugins.ts"], "Creates or promotes an installed plugin directory.", ["mkdir", "copy-file", "rename"], "(?:userPluginsDir|pluginSrc|stagedDir)"),
    ],
  }),
  defineStore({
    id: "plugin-runtime-data",
    ownerModule: "core/plugin-config.ts",
    pathPatterns: ["plugin-data/{pluginId}"],
    pathExclusions: ["plugin-data/office/jobs", "plugin-data/office/generated"],
    pathKind: "tree",
    format: "mixed-directory",
    schemaSource: {
      kind: "narrow-exemption",
      reason: "Each plugin owns its manifest-declared data contract; third-party data requires per-plugin migrationVersion registration before epoch migration.",
      expiresOn: "2026-12-31",
    },
    openEntry: ["PluginManager activation with plugin-scoped dataDir"],
    migrationEntry: ["plugin manifest/migrationVersion hook; no host-wide implicit migration"],
    checkpointPolicy: "Checkpoint by pluginId and declared migrationVersion; never infer one schema for plugin-data/**.",
    restorePolicy: "Restore only when the same pluginId and a compatible manifest/migrationVersion are available.",
    identityContract: "pluginId from the active manifest owns exactly its plugin-data subtree.",
    exemption: {
      reason: "Dynamic plugin schemas must be registered by pluginId and migrationVersion before a coordinated data migration consumes them.",
      expiresOn: "2026-12-31",
    },
    siteRules: rules([
      "core/plugin-config.ts",
      "core/media/universal-media-manager.ts",
      "plugins/image-gen/adapters/agnes.ts",
      "plugins/image-gen/index.ts",
      "plugins/image-gen/lib/download.ts",
      "plugins/image-gen/lib/local-cli-wrapper.ts",
      "plugins/image-gen/lib/task-store.ts",
      "plugins/jimeng-cli/adapters/dreamina.ts",
      "plugins/mcp/lib/mcp-runtime.ts",
    ], "Writes data within the active pluginId-scoped data directory."),
  }),
  defineStore({
    id: "plugin-development-state",
    ownerModule: "core/plugin-dev-service.ts",
    pathPatterns: ["plugins-dev/{pluginId}", "plugin-dev-runs/{runId}.json", "plugin-dev-sources/{sourceId}"],
    pathKind: "tree",
    format: "mixed-directory",
    schemaSource: directorySource("core/plugin-dev-service.ts", "dev plugin source promotion and run receipt protocol"),
    openEntry: ["PluginDevService"],
    epochPolicy: "compatible",
    checkpointPolicy: "Include user-authored sources; run receipts may be regenerated only when their source still exists.",
    identityContract: "pluginId/sourceId/runId are explicit keys; temporary paths are not identities.",
    siteRules: [
      ...rules(["core/plugin-dev-service.ts"], "Writes plugin development source or run state."),
      ...rules(["core/engine.ts"], "Creates the plugin development source root.", ["mkdir"], "pluginDevSourcesDir"),
    ],
  }),
  defineStore({
    id: "skill-state",
    ownerModule: "lib/skill-bundles/store.ts",
    pathPatterns: ["skills/{skillName}", "skill-bundles.json", ".ephemeral/skill-bundle-exports/{token}"],
    pathKind: "tree",
    format: "mixed-directory",
    schemaSource: directorySource("lib/skills/skill-package-installer.ts", "SKILL.md package, bundle registry, and export staging protocols"),
    openEntry: ["skill loader", "SkillBundleStore"],
    migrationEntry: ["core/migrations.ts skill migrations"],
    firstPossibleOpenPhase: "first_run_seed",
    firstPossibleWritePhase: "first_run_seed",
    identityContract: "skillName is identity within the user skill root; bundle IDs are registry keys.",
    siteRules: [
      ...rules(["lib/skill-bundles/package-service.ts", "lib/skill-bundles/store.ts", "lib/skills/skill-package-installer.ts", "server/utils/uploaded-skill-package.ts"], "Installs, exports, uploads, or records skill packages."),
      ...rules(["core/engine.ts"], "Creates the user skill root.", ["mkdir"], "skillsDir"),
      ...rules(["lib/character-cards/service.ts"], "Installs or renames a skill imported from a character card.", ["mkdir", "write-file"], "(?:engine[.]userSkillsDir|skillMdPath)"),
    ],
  }),
  defineStore({
    id: "operational-checkpoints",
    ownerModule: "lib/checkpoint-store.ts",
    pathPatterns: ["checkpoints/{checkpointId}"],
    pathKind: "tree",
    format: "mixed-directory",
    schemaSource: directorySource("lib/checkpoint-store.ts", "file-copy checkpoint manifest and session-manifest SQLite checkpoint protocol"),
    openEntry: ["CheckpointStore", "createSessionManifestCheckpoint"],
    epochPolicy: "compatible",
    checkpointPolicy: "This is the existing operational checkpoint facility, not an epoch checkpoint system.",
    restorePolicy: "Existing restore APIs copy declared files; they provide no cross-store epoch transaction guarantee.",
    affectedByEpochMigration: false,
    identityContract: "checkpointId names an operational snapshot; it does not establish a global data epoch.",
    siteRules: rules(["lib/checkpoint-store.ts", "core/session-manifest/checkpoint.ts"], "Writes or restores an existing operational checkpoint."),
  }),
  defineStore({
    id: "runtime-diagnostics",
    ownerModule: "lib/debug-log.ts",
    pathPatterns: [
      "logs/{timestamp}.log",
      "browser-worker.log",
      "switch-error.log",
      "user/browser-sessions.json",
      "bridge/wechat/sync-{accountHash}.json",
      "bridge/wechat/context-{accountHash}.json",
    ],
    format: "mixed-directory",
    schemaSource: directorySource("lib/debug-log.ts", "debug logs, browser cold state, switch diagnostics, and WeChat cache readers"),
    openEntry: ["runtime logging and bridge/browser startup"],
    epochPolicy: "compatible",
    checkpointPolicy: "Exclude rotating logs; browser/bridge cold state may be included as best-effort compatible cache.",
    restorePolicy: "Logs are append history; cache records may be dropped if incompatible.",
    affectedByEpochMigration: false,
    identityContract: "Diagnostic filenames are locators; browser and bridge cache keys are runtime-owned account/session keys.",
    siteRules: [
      ...rules(["lib/debug-log.ts", "lib/browser/browser-manager.ts", "lib/bridge/wechat-adapter.ts"], "Writes runtime diagnostics or recoverable cold state."),
      ...rules(["server/index.ts"], "Appends the browser worker log.", ["append-file"], "_bwsLogPath"),
      ...rules(["server/routes/sessions.ts"], "Appends switch failure diagnostics.", ["append-file"], "switch-error[.]log"),
    ],
  }),
  defineStore({
    id: "managed-runtime-caches",
    ownerModule: "lib/pi-sdk/search-tools.ts",
    pathPatterns: ["runtime/pi-sdk/bin/{toolName}", ".ephemeral/win32-sandbox-runtime/{fingerprint}"],
    pathKind: "tree",
    format: "binary-cache",
    schemaSource: directorySource("lib/pi-sdk/search-tools.ts", "managed search-tool binary and Windows sandbox runtime cache validation"),
    openEntry: ["search tool first use", "Windows sandbox runtime preparation"],
    epochPolicy: "regenerable",
    checkpointPolicy: "Excluded; validated caches are rebuilt or recopied from trusted sources.",
    restorePolicy: "Delete and regenerate on incompatibility.",
    affectedByEpochMigration: false,
    identityContract: "Cache key is tool/runtime fingerprint; cached paths are never persistent business identity.",
    siteRules: rules(["lib/pi-sdk/search-tools.ts", "lib/sandbox/win32-runtime-cache.ts"], "Populates a Hana-owned regenerable runtime cache."),
  }),
  defineStore({
    id: "legacy-pi-search-cache",
    ownerModule: "lib/pi-sdk/search-tools.ts",
    pathPatterns: [".pi/agent/bin/{toolName}"],
    pathKind: "file",
    format: "binary-cache",
    schemaSource: directorySource("lib/pi-sdk/search-tools.ts", "read-only known-binary legacy copy source"),
    openEntry: ["search tool legacy cache probe"],
    epochPolicy: "migration-source",
    checkpointPolicy: "Excluded; the legacy tree is not Hana-owned active state.",
    restorePolicy: "Never rewrite or delete; copy a recognized file lazily into runtime/pi-sdk/bin.",
    affectedByEpochMigration: false,
    identityContract: "Legacy path is a compatibility source only, not an active cache identity.",
  }),
  defineStore({
    id: "windows-sandbox-migration-state",
    ownerModule: "lib/sandbox/win32-legacy-migration.ts",
    pathPatterns: ["user/win32-sandbox-migration-v3.json", "user/win32-sandbox-cleanup-v4.json"],
    format: "json",
    schemaSource: runtimeSource("lib/sandbox/win32-legacy-migration.ts", "Windows sandbox migration marker readers"),
    openEntry: ["Windows sandbox legacy migration"],
    epochPolicy: "compatible",
    checkpointPolicy: "Include markers only with the migrated target state they describe.",
    restorePolicy: "Restore markers and migrated state together or rerun the idempotent migration.",
    affectedByEpochMigration: false,
    identityContract: "Each fixed marker records completion for one HANA_HOME.",
    siteRules: rules(["lib/sandbox/win32-legacy-migration.ts"], "Writes Windows sandbox migration markers or compatible copies."),
  }),
  defineStore({
    id: "signed-artifacts",
    ownerModule: "shared/artifact-core/pointer-store.cjs",
    pathPatterns: ["artifacts"],
    pathKind: "tree",
    format: "mixed-directory",
    schemaSource: directorySource("shared/artifact-core/pointer-store.cjs", "signed artifact pointers, verified receipts, quarantine, lock, and OTA state protocol"),
    openEntry: ["artifact activation and OTA check"],
    epochPolicy: "compatible",
    checkpointPolicy: "Exclude downloaded payload caches; preserve only if signature/pointer verification remains valid.",
    restorePolicy: "Re-verify every pointer and artifact before activation.",
    affectedByEpochMigration: false,
    identityContract: "Signed digest/version identify artifacts; pointer and staging paths are locators.",
    siteRules: rules(["shared/artifact-core/activation.cjs", "shared/artifact-core/ota-core.cjs", "shared/artifact-core/pointer-store.cjs"], "Writes signed artifact activation or OTA state."),
  }),
  defineStore({
    id: "legacy-upload-cache",
    ownerModule: "server/routes/upload.ts",
    pathPatterns: ["uploads/{uploadName}"],
    pathKind: "tree",
    format: "mixed-directory",
    schemaSource: directorySource("server/routes/upload.ts", "sessionless upload naming and age-based cleanup protocol"),
    openEntry: ["resolveUploadTarget without sessionPath"],
    firstPossibleOpenPhase: "runtime_ready",
    firstPossibleWritePhase: "runtime_ready",
    epochPolicy: "regenerable",
    checkpointPolicy: "Excluded; sessionless uploads are a short-lived compatibility cache.",
    restorePolicy: "Discard and ask the caller to upload again; age cleanup removes stale entries.",
    affectedByEpochMigration: false,
    identityContract: "Generated uploadName is a cache locator, not a durable file or session identity.",
  }),
  defineStore({
    id: "character-card-staging",
    ownerModule: "lib/character-cards/service.ts",
    pathPatterns: [
      ".ephemeral/character-card-uploads/{fileName}",
      ".ephemeral/character-card-imports/{token}",
      ".ephemeral/character-card-exports/{token}",
    ],
    pathKind: "tree",
    format: "mixed-directory",
    schemaSource: directorySource("lib/character-cards/service.ts", "token-scoped import plan/package and export package protocol"),
    openEntry: ["character card upload, import planning, or export"],
    firstPossibleOpenPhase: "runtime_ready",
    firstPossibleWritePhase: "runtime_ready",
    epochPolicy: "regenerable",
    checkpointPolicy: "Excluded; plans and packages are request-scoped staging.",
    restorePolicy: "Discard incomplete tokens and restart import/export from the original package.",
    affectedByEpochMigration: false,
    identityContract: "Random token owns one staging subtree; staged paths never become agent or skill identities.",
    siteRules: [
      ...rules(["server/routes/character-cards.ts"], "Writes a bounded character-card upload package."),
      ...rules(["lib/character-cards/service.ts"], "Writes a token-scoped character-card import/export plan or package.", ["mkdir", "write-file", "copy-file", "atomic-write"], "(?:filePath, JSON[.]stringify|packageRoot|stageDir)"),
    ],
  }),
  defineStore({
    id: "desk-cover-upload-staging",
    ownerModule: "server/routes/desk.ts",
    pathPatterns: ["tmp/markdown-cover-uploads/{token}"],
    pathKind: "tree",
    format: "directory-tree",
    schemaSource: directorySource("server/routes/desk.ts", "bounded base64 cover upload temporary-directory lifecycle"),
    openEntry: ["writeUploadedCoverImage"],
    firstPossibleOpenPhase: "runtime_ready",
    firstPossibleWritePhase: "runtime_ready",
    epochPolicy: "regenerable",
    checkpointPolicy: "Excluded; each cover upload is request-scoped temporary input.",
    restorePolicy: "Delete the temporary directory and upload the cover again.",
    affectedByEpochMigration: false,
    identityContract: "Temporary directory token owns the upload bytes; the final Markdown attachment has separate workspace ownership.",
    siteRules: rules(["server/routes/desk.ts"], "Writes a bounded temporary cover upload.", ["mkdir", "write-file"], "(?:uploadRoot|filePath, buffer)"),
  }),
  defineStore({
    id: "office-render-jobs",
    ownerModule: "plugins/office/lib/html-to-pdf.ts",
    pathPatterns: ["plugin-data/office/jobs", "plugin-data/office/generated"],
    pathKind: "tree",
    format: "mixed-directory",
    schemaSource: directorySource("plugins/office/lib/html-to-pdf.ts", "job.json/input.html request contract and generated PDF output lifecycle"),
    openEntry: ["renderHtmlToPdf"],
    firstPossibleOpenPhase: "runtime_ready",
    firstPossibleWritePhase: "runtime_ready",
    epochPolicy: "regenerable",
    checkpointPolicy: "Excluded; jobs are request-scoped and generated PDFs are re-creatable outputs.",
    restorePolicy: "Discard incomplete jobs; rerun rendering from source HTML when output is still needed.",
    affectedByEpochMigration: false,
    identityContract: "jobId scopes one render request; outputPath is a locator and SessionFile registration supplies durable session ownership.",
    siteRules: rules(["plugins/office/lib/html-to-pdf.ts"], "Writes an office render job input, receipt, or generated output."),
  }),
  defineStore({
    id: "plugin-download-cache",
    ownerModule: "server/routes/plugins.ts",
    pathPatterns: ["plugin-install-sources/{pluginId}/{version}"],
    pathKind: "tree",
    format: "binary-cache",
    schemaSource: directorySource("server/routes/plugins.ts", "verified plugin release ZIP naming by pluginId/version and expected sha256"),
    openEntry: ["downloadMarketplacePluginRelease"],
    firstPossibleOpenPhase: "runtime_ready",
    firstPossibleWritePhase: "runtime_ready",
    epochPolicy: "regenerable",
    checkpointPolicy: "Excluded; packages can be downloaded again and must pass sha256 verification.",
    restorePolicy: "Re-verify sha256 before reuse, otherwise delete and redownload.",
    affectedByEpochMigration: false,
    identityContract: "pluginId/version identify the source generation; ZIP path is a verified cache locator.",
    siteRules: rules(["server/routes/plugins.ts"], "Caches a sha256-verified plugin release package.", ["mkdir", "write-file"], "(?:downloadsDir|packagePath)"),
  }),
]);

function exemption(
  id: string,
  ownerModule: string,
  sourceFile: string,
  reason: string,
  expiresOn: string,
  kinds: readonly PersistenceSiteKind[] = ALL_SITE_KINDS,
  linePattern?: string,
): PersistenceExemption {
  return Object.freeze({
    id,
    ownerModule,
    sourceFile,
    reason,
    expiresOn,
    kinds: [...kinds],
    ...(linePattern ? { linePattern } : {}),
  });
}

export const PERSISTENCE_EXEMPTIONS: readonly PersistenceExemption[] = Object.freeze([
  exemption(
    "in-memory-confirm-registry",
    "lib/confirm-store.ts",
    "server/index.ts",
    "ConfirmStore is deliberately process-memory-only: pending approvals time out or abort with their session and have no restart replay contract.",
    "2027-01-31",
    ["persistent-store-constructor"],
    "ConfirmStore",
  ),
  exemption(
    "compat-directory-seeding",
    "lib/compat/checks/dirs.ts",
    "lib/compat/checks/dirs.ts",
    "Compatibility check creates a fixed set of registered HANA_HOME roots; flow attribution remains with the first-run coordinator.",
    "2026-10-31",
  ),
  exemption(
    "cross-store-first-run-bootstrap",
    "core/first-run.ts",
    "core/first-run.ts",
    "First-run seeds several registered stores from packaged templates. Flow-sensitive attribution moves into the future coordinator; this exact composition file is not ignored by directory.",
    "2026-10-31",
  ),
  exemption(
    "cross-store-legacy-migrations",
    "core/migrations.ts",
    "core/migrations.ts",
    "The legacy migration orchestrator mutates many registered targets. Each target is inventoried, while exact-site flow attribution remains prerequisite work for the coordinator.",
    "2026-10-31",
  ),
  exemption(
    "conditional-upload-target",
    "server/routes/upload.ts",
    "server/routes/upload.ts",
    "resolveUploadTarget sends the same syntactic write sites to registered session-files storage when sessionPath is present or to the registered legacy uploads cache otherwise; flow-sensitive site attribution is required to distinguish them.",
    "2026-10-31",
    ["mkdir", "copy-file", "write-file"],
  ),
  exemption(
    "server-identity-atomic-helper",
    "core/server-identity.ts",
    "core/server-identity.ts",
    "The file-local atomic helper receives paths only from the separately registered server-node and user/studio registry call sites.",
    "2026-10-31",
    ["mkdir", "atomic-write"],
    "(?:path[.]dirname\\(filePath\\)|atomicWriteSync\\(filePath)",
  ),
  exemption(
    "local-user-account-atomic-helper",
    "core/local-user-account.ts",
    "core/local-user-account.ts",
    "The file-local atomic helper receives paths only from the separately registered users.json and local-user-auth.json call sites.",
    "2026-10-31",
    ["mkdir", "atomic-write"],
    "(?:path[.]dirname\\(filePath\\)|atomicWriteSync\\(filePath)",
  ),
  exemption(
    "character-card-copy-helper",
    "lib/character-cards/service.ts",
    "lib/character-cards/service.ts",
    "The file-local copy helper is flow-dependent: callers target either token-scoped card staging or an explicitly registered skill destination.",
    "2026-10-31",
    ["mkdir", "copy-file"],
    "(?:path[.]dirname\\(dst\\)|sourcePath, dst)",
  ),
  exemption(
    "external-desk-workspace-roots",
    "server/routes/desk.ts",
    "server/routes/desk.ts",
    "Creates an approved external workspace root or its .agents/skills directory; the mount registry owns authorization, not the external content.",
    "2027-01-31",
    ["mkdir"],
    "(?:skillsDir|fs[.]mkdirSync\\(dir|baseDir)",
  ),
  exemption(
    "external-beautify-markdown-output",
    "plugins/beautify/lib/markdown-cover-service.ts",
    "plugins/beautify/lib/markdown-cover-service.ts",
    "Copies a generated cover beside an explicitly selected workspace Markdown file and atomically updates that external file.",
    "2027-01-31",
  ),
  exemption(
    "external-mount-writes",
    "core/mount-aware-file-service.ts",
    "core/mount-aware-file-service.ts",
    "Creates user-selected workspace or mounted roots whose ownership is recorded by studio-mounts.json rather than by HANA_HOME path inventory.",
    "2027-01-31",
  ),
  exemption(
    "external-resource-io",
    "lib/resource-io/providers/local-fs-provider.ts",
    "lib/resource-io/providers/local-fs-provider.ts",
    "Writes explicit user-selected local filesystem resource targets outside Hana persistence ownership.",
    "2027-01-31",
  ),
  exemption(
    "external-file-ref-io",
    "lib/file-ref/resource-io.ts",
    "lib/file-ref/resource-io.ts",
    "Writes an explicit tool output path supplied by the caller; no HANA_HOME store is implied.",
    "2027-01-31",
  ),
  exemption(
    "external-default-workspace",
    "shared/default-workspace.ts",
    "shared/default-workspace.ts",
    "Creates the user-selected default workspace outside HANA_HOME.",
    "2027-01-31",
  ),
  exemption(
    "external-heartbeat-workspace",
    "lib/desk/heartbeat.ts",
    "lib/desk/heartbeat.ts",
    "Writes heartbeat/task files inside an explicitly mounted workspace, not a Hana-owned persistence root.",
    "2027-01-31",
  ),
  exemption(
    "windows-uia-request-temp",
    "core/computer-use/providers/windows-uia-provider.ts",
    "core/computer-use/providers/windows-uia-provider.ts",
    "Creates helper/request files in the operating-system temporary directory for one Windows UIA call.",
    "2027-01-31",
  ),
  exemption(
    "generic-safe-fs-primitives",
    "shared/safe-fs.ts",
    "shared/safe-fs.ts",
    "Shared atomic-write primitives have no store ownership; callers are scanned and assigned to concrete descriptors.",
    "2027-01-31",
  ),
  exemption(
    "generic-archive-writer",
    "shared/artifact-core/ustar.cjs",
    "shared/artifact-core/ustar.cjs",
    "The archive codec writes caller-selected archive/extraction paths; signed artifact ownership is assigned at its callers.",
    "2027-01-31",
  ),
  exemption(
    "generic-zip-writer",
    "lib/zip-writer.ts",
    "lib/zip-writer.ts",
    "The ZIP codec writes a caller-selected destination and has no independent persistent store.",
    "2027-01-31",
  ),
  exemption(
    "sandbox-command-output",
    "lib/exec-command/runner.ts",
    "lib/exec-command/runner.ts",
    "Writes command output to an explicit tool-selected path under the active sandbox/workspace.",
    "2027-01-31",
  ),
  exemption(
    "sandbox-script-output",
    "lib/sandbox/script.ts",
    "lib/sandbox/script.ts",
    "Writes a generated script into a request-scoped sandbox or operating-system temporary directory.",
    "2027-01-31",
  ),
  exemption(
    "sandbox-office-media-temp",
    "lib/sandbox/read-office-media.ts",
    "lib/sandbox/read-office-media.ts",
    "Writes extracted office media to a request-scoped temporary directory.",
    "2027-01-31",
  ),
  exemption(
    "sandbox-win32-command-temp",
    "lib/sandbox/win32-exec.ts",
    "lib/sandbox/win32-exec.ts",
    "Writes a request-scoped Windows command wrapper outside persistent Hana state.",
    "2027-01-31",
  ),
  exemption(
    "url-provider-download-temp",
    "lib/resource-io/providers/url-provider.ts",
    "lib/resource-io/providers/url-provider.ts",
    "Writes a bounded network download to the caller-selected resource destination.",
    "2027-01-31",
  ),
  exemption(
    "config-scope-migration-helper",
    "shared/migrate-config-scope.ts",
    "shared/migrate-config-scope.ts",
    "Compatibility helper mutates a caller-supplied config file; concrete agent config ownership is registered at callers.",
    "2026-10-31",
  ),
]);
